<?php

namespace kenjis\OreOrePHP;

use AspectMock\Test as test;
use Mockery as m;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-01-18 at 15:42:28.
 */
class FrameworkTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Framework
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        test::clean();
        m::close();
    }

    /**
     * @covers kenjis\OreOrePHP\Framework::run
     */
    public function testRun_Success_AspectMock()
    {
        $dice = test::double('Jasrags\Dice')->make();
        $twig = test::double('Twig_Environment')->make();
        $hello = test::double(
            'Controller\Hello',
            ['run' => 'I am world.', 'injectCoreDependancy' => null]
        )->construct($twig);
        $container = test::double(
            'kenjis\OreOrePHP\Container\Dice',
            ['resolve' => function () use ($hello) {
                return $hello;
            }]
        )->construct($dice);
        $config = test::double('kenjis\OreOrePHP\Config')->construct([]);
        $router = test::double(
            'kenjis\OreOrePHP\Router\Pux',
            ['getRoute' => ['Hello', 'actionSay', ['world', null, null]]]
        )->make();
        $request = test::double('kenjis\OreOrePHP\Request')->make();
        $response = test::double(
            'kenjis\OreOrePHP\Response',
            ['setBody' => null, 'send' => 'I am world.']
        )->make();
        
        $object = new Framework($container, $config, $router, $request, $response);
        $test = $object->run();
        $expected = '';
        $this->assertEquals($expected, $test);
    }
    
    /**
     * @covers kenjis\OreOrePHP\Framework::run
     */
    public function testRun_Success_Mocery()
    {
        $dice = m::mock('Jasrags\Dice');
        $twig = m::mock('Twig_Environment');
        $config = m::mock('kenjis\OreOrePHP\Config');
        $router = m::mock('kenjis\OreOrePHP\Router\Pux')
            ->shouldReceive('getRoute')
            ->andReturn(['Hello', 'actionSay', ['world', null, null]])
            ->getMock();
        $request = m::mock('kenjis\OreOrePHP\Request');
        $response = m::mock('kenjis\OreOrePHP\Response')
            ->shouldReceive('setBody')->with('I am world.')->andReturn(null)
            ->getMock();
        $response->shouldReceive('send')->andReturn('I am world.');
        $hello = m::mock('Controller\Hello');
        $hello->shouldReceive('run')->andReturn('I am world.');
        $hello->shouldReceive('injectCoreDependancy')->with()->andReturn(null);
        $container = m::mock('kenjis\OreOrePHP\Container\Dice')
            ->shouldReceive('resolve')->with('Controller\Hello')->andReturn($hello)
            ->getMock();
        
        $object = new Framework($container, $config, $router, $request, $response);
        $test = $object->run();
        $expected = '';
        $this->assertEquals($expected, $test);
    }
    
    /**
     * 
     */
    public function testRun_ControllerNotFound()
    {
        $dice = m::mock('Jasrags\Dice');
        $twig = m::mock('Twig_Environment');
        $config = m::mock('kenjis\OreOrePHP\Config');
        $router = m::mock('kenjis\OreOrePHP\Router\Pux')
            ->shouldReceive('getRoute')
            ->andReturn(['Notfound', 'actionNotfound', [null, null, null]])
            ->getMock();
        $request = m::mock('kenjis\OreOrePHP\Request');
        $response = m::mock('kenjis\OreOrePHP\Response');
        $response->shouldReceive('setStatusCode')->with(404)->andReturn(null);
        $container = m::mock('kenjis\OreOrePHP\Container\Dice');
        
        $this->expectOutputString('Controller\Notfound is not found.');
        $object = new Framework($container, $config, $router, $request, $response);
        $test = $object->run();
    }

}
